name: 'GitHub Action for Mackerel API'
description: 'Call a Mackerel API endpoint and get the resulting JSON response.'
author: 'yutailang0119'
inputs:
  server-url:
    description: 'The server url. e.g. "https://api.mackerelio.com"'
    default: 'https://api.mackerelio.com'
  api-key:
    description: 'API key for Mackerel - generate one at https://mackerel.io/my?tab=apikeys'
    required: true
  http-method:
    description: 'The HTTP method. e.g. GET / POST'
    default: 'GET'
  version:
    description: 'The API version. e.g "v0"'
    default: 'v0'
  path:
    description: 'The endpoint path. e.g. "hosts/<hostId>/metadata/<namespace>"'
    required: true
  body:
    description: 'The request body string in JSON or hash format'
    default: ''
  dry-run:
    description: 'Do not call Mackerel API. Just prints out.'
    default: 'false'
outputs:
  result:
    description: 'The return value of called API, stringified with `JSON.stringify`'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'blue'
