name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - run: |
          npm install
      - run: |
          npm run all
        env:
          TEST_API_KEY: ${{ secrets.MACKEREL_API_KEY }}
          TEST_ORG_NAME: ${{ secrets.MACKEREL_ORG_NAME }}
          TEST_SERVICE_NAME: ${{ secrets.MACKEREL_SERVICE_NAME }}
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./
        with:
          api-key: ${{ secrets.MACKEREL_API_KEY }}
          path: org
          dry-run: true
